before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - ./check-ain-version.sh {{ .Tag }}
builds:
  - main: ./cmd/ain/main.go
    ldflags:
      - -s -w -X main.gitSha={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: mac_os
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - assets/*
    wrap_in_directory: true
brews:
  - tap:
      owner: jonaslu
      name: homebrew-tools
    commit_author:
      name: Jonas Lundberg
      email: jonasl@iamjonas.me
    homepage: "https://github.com/jonaslu/ain"
    description: "Ain is a terminal API client. It's an alternative to postman, paw or insomnia."
    license: MIT
scoop:
  bucket:
    owner: jonaslu
    name: scoop-tools
  homepage: "https://github.com/jonaslu/ain"
  description: "Ain is a terminal API client. It's an alternative to postman, paw or insomnia."
  license: MIT
release:
  draft: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
