before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - ./check-ain-version.sh {{ .Tag }}
builds:
  - main: ./cmd/ain/main.go
    ldflags:
      - -s -w -X main.gitSha={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - id: default
    name_template: >-
          {{- .ProjectName }}_
          {{- .Version }}_
          {{- if eq .Os "darwin"}}mac_os
          {{- else }}{{ tolower .Os }}{{ end }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - assets/*
      - README.md
      - LICENSE
    wrap_in_directory: true
brews:
  - repository:
      owner: jonaslu
      name: homebrew-tools
    commit_author:
      name: Jonas Lundberg
      email: jonasl@iamjonas.me
    homepage: "https://github.com/jonaslu/ain"
    description: "Ain is a terminal API client. It's an alternative to postman, paw or insomnia."
    license: MIT
scoops:
  - repository:
      owner: jonaslu
      name: scoop-tools
    homepage: "https://github.com/jonaslu/ain"
    description: "Ain is a terminal API client. It's an alternative to postman, paw or insomnia."
    license: MIT
release:
  draft: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
